=== mkurlit/UOY/AP/Activities/Week 2/Activity 1/class.dtd
<!ELEMENT class (student*)>
<!ELEMENT student (name, middlename?, surname, id, module*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT middlename (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT module (module_name, assignment*)>
<!ELEMENT module_name (#PCDATA)>
<!ELEMENT assignment (type, sequence, score)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT sequence (#PCDATA)>
<!ELEMENT score (#PCDATA)>

=== mkurlit/UOY/AP/Activities/Week 2/Activity 1/student.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE class SYSTEM "class.dtd"> 
<class>
    <student>
        <name>Sara</name>
        <middlename>K.</middlename>
        <surname>Beck</surname>
        <id>16720905-9422</id>
        <module>
            <module_name>Mathematics</module_name>
            <assignment>
                <type>Test</type>
                <sequence>1</sequence>
                <score>.66</score>
            </assignment>
            <assignment>
                <type>Test</type>
                <sequence>2</sequence>
                <score>.57</score>
            </assignment>
        </module>
        <module>
            <module_name>English</module_name>
            <assignment>
                <type>Essay</type>
                <sequence>1</sequence>
                <score>C-</score>
            </assignment>
            <assignment>
                <type>Essay</type>
                <sequence>2</sequence>
                <score>D+</score>
            </assignment>
        </module>
        <module>
            <module_name>IT</module_name>
            <assignment>
                <type>Activity</type>
                <sequence>1</sequence>
                <score>Pass</score>
            </assignment>
            <assignment>
                <type>Test</type>
                <sequence>2</sequence>
                <score>.41</score>
            </assignment>
            <assignment>
                <type>Essay</type>
                <sequence>3</sequence>
                <score>C-</score>
            </assignment>
        </module>
    </student>
</class>
